apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shinobi-config-pvc
spec:
  accessModes:
    - ReadWriteMany  # Use the appropriate access mode
  storageClassName: manual  # Use the appropriate StorageClass
  resources:
    requests:
      storage: 1Gi  # Adjust the storage capacity to match the PV
  volumeName: shinobi-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shinobi-mysql-pvc
spec:
  accessModes:
    - ReadWriteMany  # Use the appropriate access mode (ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
  storageClassName: manual  # Use the appropriate StorageClass
  resources:
    requests:
      storage: 1Gi  # Request the amount of storage you need
  volumeName: shinobi-mysql-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shinobi-streams-pvc
spec:
  accessModes:
    - ReadWriteMany  # Use the appropriate access mode
  storageClassName: manual  # Use the appropriate StorageClass
  resources:
    requests:
      storage: 1Gi  # Adjust the storage capacity to match the PV
  volumeName: shinobi-streams-pv