---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shinobi-config-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # Use appropriate access mode (ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
  persistentVolumeReclaimPolicy: Retain  # Use Retain, Recycle, or Delete as needed
  storageClassName: manual  # Use the appropriate StorageClass
  nfs:
    path: /mnt/nfs_mount
    server: #IP
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shinobi-mysql-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # Use appropriate access mode (ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
  persistentVolumeReclaimPolicy: Retain  # Use Retain, Recycle, or Delete as needed
  storageClassName: manual  # Use the appropriate StorageClass
  nfs:
    path: /mnt/nfs_mount
    server: #IP
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shinobi-streams-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # Use appropriate access mode (ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
  persistentVolumeReclaimPolicy: Retain  # Use Retain, Recycle, or Delete as needed
  storageClassName: manual  # Use the appropriate StorageClass
  nfs:
    path: /mnt/nfs_mount
    server: #IP
    readOnly: false