apiVersion: v1
kind: Secret
metadata:
  name: shinobi-secret
type: Opaque
data:
  ADMIN_USER: #BASE_64_ENCODED           #YOU CAN REFRENCE THEM AS WELL.
  ADMIN_PASSWORD: #BASE_64_ENCODED     
  MYSQL_ROOT_PASSWORD: #BASE_64_ENCODED
  MYSQL_USER: #BASE_64_ENCODED             #YOU CAN REFRENCE THEM AS WELL.
  MYSQL_PASSWORD: #BASE_64_ENCODED
